### ISSUE TITLE
Corrupted zip files

### ISSUE THREAD

**Issue by nainamaharjan** [s-sauer/tissue-simulation-pipeline#1]
Biophysical_simulation.zip and segmentation_seg.npy.zip file are corrupted and does not open.

**Comment by s-sauer** [comment]
Thanks for raising this issue. I downloaded the files and extracted them, works fine for me.
Have you downloaded them directly with the browser from github's web-interface, or did you clone the repo? In the latter case, the problem could be due to the [_Git Large File Storage_](https://git-lfs.com/) extension that I used to upload the `zip` files. If so, please either
* try downloading the files directly with your browser.
* or install the [_Git Large File Storage_](https://git-lfs.com/) extension and try to clone the repo again.

**Comment by nainamaharjan** [comment]
I did clone it from the github repository. I will try downloading it and
let you know. Thank you.
